# Generated by Django 4.0.5 on 2022-06-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=15)),
                ('location', models.CharField(max_length=140)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('profile_picture', models.ImageField(blank=True, upload_to='thumbpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', unique=True)),
            ],
        ),
    ]
